# Generated by Django 4.0.6 on 2022-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='/Users/new/VSCodeProjects/dj_ds/src/media/no_photo.png', upload_to='customers'),
        ),
    ]
