# Generated by Django 4.0.6 on 2022-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='no_photo.png', upload_to='customers'),
        ),
    ]
